language: ruby
sudo: false
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
env:
  - RAILS_VERSION=4
  - RAILS_VERSION=5.1
  - RAILS_VERSION=5.2
  - RAILS_VERSION=master
script:
  - bundle exec rake
matrix:
  allow_failures:
    - env: RAILS_VERSION=master
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
