services:
  dev:
    build: 
      context: .
      args:
        RUBY_VERSION: $RUBY_VERSION
        RAILS_VERSION: $RAILS_VERSION
  ruby2_6_rails4:
    build: 
      context: .
      args:
        RUBY_VERSION: 2.6.6
        RAILS_VERSION: 4
