# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52c44ac87bd5a7e5a3b25da95d8ed592d6d8da9f6320320267f50564be0f707ef871d6eeba0655876dc32baf7fdbd007a43180d9a96409c0a461c5cdd7ba4f2e

test:
  secret_key_base: 649b9428bc9a565b617c5a8c69e0f4ba1c1de84bc0c7f50adbe2eac0fc80be685db2b47abb5e84e80a831783475dd29136ab97be16a02f32a664e47129f4a619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
