build_and_push: &build_and_push 
  docker:
    - image: quay.io/nyulibraries/circleci_docker:19.03.13-dc-1.27.4-0
  working_directory: ~/app
  steps:
    - checkout
    - setup_remote_docker:
        version: 20.10.6
    - run:
        name: Build image
        command: |
          docker-compose build dev
    - run:
        name: Run test
        command: |
          docker-compose run dev

version: 2
jobs:
  ruby2_4_rails4:
    <<: *build_and_push
    environment:
      RUBY_VERSION: 2.4.6
      RAILS_VERSION: 4
  ruby2_5_rails4:
    <<: *build_and_push
    environment:
      RUBY_VERSION: 2.5.5
      RAILS_VERSION: 4
  ruby2_6_rails4:
    <<: *build_and_push
    environment:
      RUBY_VERSION: 2.6.3
      RAILS_VERSION: 4
  ruby2_4_rails5_1:
    <<: *build_and_push
    environment:
      RUBY_VERSION: 2.4.6
      RAILS_VERSION: 5.1
  ruby2_5_rails5_1:
    <<: *build_and_push
    environment:
      RUBY_VERSION: 2.5.5
      RAILS_VERSION: 5.1
  ruby2_6_rails5_1:
    <<: *build_and_push
    environment:
      RUBY_VERSION: 2.6.3
      RAILS_VERSION: 5.1
  ruby2_4_rails5_2:
    <<: *build_and_push
    environment:
      RUBY_VERSION: 2.4.6
      RAILS_VERSION: 5.2
  ruby2_5_rails5_2:
    <<: *build_and_push
    environment:
      RUBY_VERSION: 2.5.5
      RAILS_VERSION: 5.2
  ruby2_6_rails5_2:
    <<: *build_and_push
    environment:
      RUBY_VERSION: 2.6.3
      RAILS_VERSION: 5.2

workflows:
  version: 2
  build-and-deliver:
    jobs:
      - ruby2_4_rails4
      - ruby2_5_rails4
      - ruby2_6_rails4
      - ruby2_4_rails5_1
      - ruby2_5_rails5_1
      - ruby2_6_rails5_1
      - ruby2_4_rails5_2
      - ruby2_5_rails5_2
      - ruby2_6_rails5_2
